# Site settings
title: "Resume- Navendu"
description: "Navendu - Machine Learning Engineer"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Navendu Niranjan P"
resume_title:                   "Machine Learning Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "navendupottekkat@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+91-9567210454"
resume_contact_address:         "Kochi, India"

resume_header_contact_info:     "+91-9567210454 • navendupottekkat@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Machine Learning Engineer with a strong commitment to open-source working in bringing Computer Vision and Deep Learning to edge devices. Passionate about learning and sharing my knowledge with the community.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
# resume_section_skills:          true
# resume_section_recognition:     false
resume_section_links:           true
# resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/navendu-pottekkat"
  resume_twitter_url:           "http://twitter.com/navendu_23"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://www.facebook.com/navendupottekkat/"
  resume_linkedin_url:          "https://www.linkedin.com/in/navendup"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://navendu.me"
  resume_medium_url:            "https://medium.com/@navendupottekkat"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
